get notes comments
shuangpan5217/2021-fall-cs160-team-Mochi pull request #163
Opened 2021-10-31 04:15 UTC by VZFV

![1635653563(1)](https://user-images.githubusercontent.com/23178326/139567338-e7460722-dc0c-4b42-8f3e-2d60f3bebfc0.jpg)

2021-10-31 19:23 UTC, sue627 approved these changes
![image](https://user-images.githubusercontent.com/52468728/139598310-d77a2638-b31b-4093-aac2-01a40564088b.png)
![image](https://user-images.githubusercontent.com/52468728/139598359-55648f4c-cffb-4fc5-8667-76132fcd365e.png)

reviewed and tested. the code is looks good to me, and the test result is works.

2021-10-31 21:58 UTC, shp076 requested changes
Bugs with comments resp. Return same contents.
DB:
![image](https://user-images.githubusercontent.com/89820657/139602476-f6839cdb-3a73-4b94-812c-b9b4e4c9b7c8.png)

Resp: 
![image](https://user-images.githubusercontent.com/89820657/139602481-aef9b555-61cc-4cc8-bbdd-9f0cbec45306.png)

2021-10-31 21:58 UTC, shp076 commented on backend/source/apis/notes/get_notes_comments.go
> +	for rows.Next() {
Move line 59 inside the loop can fix bugs.

2021-10-31 22:06 UTC, shp076 requested changes

2021-10-31 22:06 UTC, shp076 commented on backend/source/apis/notes/get_notes_comments.go
> +				WHERE note_id = ?`
Also return `comment_id`, it can be used in `DELETE /v1/comments/{id}`

2021-11-01 00:23 UTC, VZFV commented
![1635726211(1)](https://user-images.githubusercontent.com/23178326/139606444-8a021119-6596-4a1f-8b3d-de5ee1bfe7e2.jpg)

2021-11-01 00:56 UTC, shp076 approved these changes
Looks good

2021-11-01 00:57 UTC, merged