Personal Page - My Note and Connect to Backend
shuangpan5217/2021-fall-cs160-team-Mochi pull request #216
Opened 2021-11-20 12:06 UTC by dawndawnwong

- Personal page my note UI Implementation
- Personal page my note connect to the backend

2021-11-22 23:02 UTC, aprilemeraldchao requested changes
I just made a few comments on your code. I haven't had time to pull and review the actual UI yet :)

2021-11-22 23:02 UTC, aprilemeraldchao commented on frontend/src/pages/PersonalPage.jsx
> +                                {pdf.map((eachDPF) => (
typo -> ``eachPDF``

2021-11-22 23:02 UTC, aprilemeraldchao commented on frontend/src/pages/PersonalPage.jsx
> +                                        <PersonalPagePDFViewer
I think we can add an onclick function to the pdf viewer instead of wrapping it with a link, but that's personal preference

2021-11-25 03:35 UTC, dawndawnwong commented on frontend/src/css/personalPage.css
> +    max-height: calc(90vh);
Removed it.

2021-11-25 03:36 UTC, dawndawnwong commented on frontend/src/css/personalPage.css
> +    max-height: calc(60vh);
Removed it.

2021-11-25 03:46 UTC, dawndawnwong commented on frontend/src/pages/PersonalPage.jsx
> +                "http://localhost:3000/v1/notes/file/" + note.note_reference,
We do not have api for GET multiple pdf files.

2021-11-25 03:52 UTC, dawndawnwong commented on frontend/src/pages/PersonalPage.jsx
> +                                {pdf.map((eachDPF) => (
Fixed it.

2021-11-25 03:53 UTC, dawndawnwong commented on frontend/src/pages/PersonalPage.jsx
> +    const [pdf, setPDF] = useState([]);
It does not work if I change to pdfs and setPDFs, it always show "loading pdf"

2021-11-25 03:56 UTC, dawndawnwong commented on frontend/src/components/personalPagePDFViewer.jsx
> +function PersonalPagePDFViewer({ pdf }) {
PDFViewer component already has thumbnail scale 0.4 and 1.5. I need  a 0.75 scale

2021-11-25 13:24 UTC, aprilemeraldchao commented on frontend/src/components/personalPagePDFViewer.jsx
> +function PersonalPagePDFViewer({ pdf }) {
0.75 looks quite large to me: 
![image](https://user-images.githubusercontent.com/58454072/143449346-07cb309b-a313-487c-ac49-21fba41baba5.png)

2021-11-25 13:26 UTC, aprilemeraldchao commented on frontend/src/css/personalPage.css
> +    max-height: calc(90vh);
Sorry, I think the issue was that you shouldn't just use vh but use something along the lines of ``calc(90vh - 200px)``. I'm not sure about the actual numbers but you could play around with different browser heights. It looks too short for me
![image](https://user-images.githubusercontent.com/58454072/143449738-6d91a3d2-c8bb-4a9b-afba-16c243e0f4da.png)

2021-11-25 13:27 UTC, aprilemeraldchao commented on frontend/src/css/personalPage.css
> +    max-height: calc(60vh);
Sorry, I think the issue was that you shouldn't just use vh but use something along the lines of ``calc(90vh - 200px)``. I'm not sure about the actual numbers but you could play around with different browser heights. It looks too short for me
![image](https://user-images.githubusercontent.com/58454072/143449738-6d91a3d2-c8bb-4a9b-afba-16c243e0f4da.png)

2021-11-25 13:28 UTC, aprilemeraldchao commented on frontend/src/pages/PersonalPage.jsx
> +    const [pdf, setPDF] = useState([]);
Changing variable names shouldn't affect the logic. Maybe you missed something when refactoring?

2021-11-25 13:29 UTC, aprilemeraldchao commented on frontend/src/pages/PersonalPage.jsx
> +                "http://localhost:3000/v1/notes/file/" + note.note_reference,
Sorry, should've mentioned that it's actually a POST method. Hard to notice: 
![image](https://user-images.githubusercontent.com/58454072/143450091-99f64248-9a41-4e32-8377-fff3c3ab9dbc.png)

2021-11-29 02:54 UTC, dawndawnwong commented on frontend/src/pages/PersonalPage.jsx
> +    const [pdf, setPDF] = useState([]);
Changed it.

2021-11-29 02:54 UTC, dawndawnwong commented on frontend/src/components/personalPagePDFViewer.jsx
> +function PersonalPagePDFViewer({ pdf }) {
Changed it to 0.6

2021-11-29 03:22 UTC, dawndawnwong commented on frontend/src/css/personalPage.css
> +    max-height: calc(90vh);
Changed it to calc(100vh - 230px).

2021-11-29 03:24 UTC, dawndawnwong commented on frontend/src/css/personalPage.css
> +    max-height: calc(60vh);
Changed it to calc(100vh - 230px).

2021-11-29 04:00 UTC, dawndawnwong commented on frontend/src/pages/PersonalPage.jsx
> +                "http://localhost:3000/v1/notes/file/" + note.note_reference,
I added it to the backlog.

2021-11-29 05:05 UTC, aprilemeraldchao requested changes
The group page upload is a bit broken.

## Punted Changes (already in backlog that should be done before the demo)
The layout is still messed up. 
![image](https://user-images.githubusercontent.com/58454072/143810429-5f2b812c-40f6-4693-b0b3-98c25493e24f.png)

2021-11-29 05:05 UTC, aprilemeraldchao commented on frontend/src/components/uploadNotesWindow.jsx
> +        if (groupId) {
also you should only attempt to add members if the share setting is "shared"

2021-11-29 09:33 UTC, aprilemeraldchao approved these changes
Looks good! Nice job fixing the layout too. I think it's fine for now that it breaks when the window is too small (my parts do that too haha)

2021-11-29 18:43 UTC, merged